/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prototype;

import java.awt.Image;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ariarf
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        Image icon = new ImageIcon(this.getClass().getResource("IconApp.png")).getImage();
        this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inputNama = new javax.swing.JTextField();
        inputNomorHp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputC1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        inputC2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        inputC3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        inputC5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        inputC4 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        inputCari = new javax.swing.JTextField();
        btnMulaiSeleksi = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnBersihkan = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nama");

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SSRO ASLAB FT UNKRIS");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Nomor HP");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("IPK (C1)");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Wawancara (C2)");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Microteaching (C3)");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Kepribadian (C4)");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Tes Tertulis (C5)");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        inputC4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kepribadian", "Sangat Baik", "Baik", "Cukup Baik", "Kurang Baik", "Tidak Baik" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputNama)
                    .addComponent(inputNomorHp)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9)
                            .addComponent(inputC3)
                            .addComponent(inputC5)
                            .addComponent(inputC1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(13, 17, Short.MAX_VALUE))
                            .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputC2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(inputC4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputNomorHp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputC1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputC2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputC3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputC4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputC5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        inputCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputCariKeyPressed(evt);
            }
        });

        btnMulaiSeleksi.setText("Mulai Seleksi");
        btnMulaiSeleksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulaiSeleksiActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Cari");

        btnBersihkan.setText("Bersihkan");
        btnBersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBersihkanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputCari, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                .addComponent(btnBersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMulaiSeleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputCari, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMulaiSeleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(btnBersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Nomor HP", "C1", "C2", "C3", "C4", "C5", "Total", "Diterima"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prototype/Desktop - 1.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clear() {
        inputNama.setText("");
        inputNomorHp.setText("");
        inputC1.setText("");
        inputC2.setText("");
        inputC3.setText("");
        inputC4.setSelectedIndex(0);
        inputC5.setText("");
    }
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        
        if (inputC4.getSelectedItem() != "Pilih Kepribadian") {
            if (btnSimpan.getText() == "Simpan") {
                model.addRow(new Object[] {
                   inputNama.getText(),
                   inputNomorHp.getText(),
                   inputC1.getText(),
                   inputC2.getText(),
                   inputC3.getText(),
                   inputC4.getSelectedItem().toString(),
                   inputC5.getText()
               });   
            } else if (btnSimpan.getText() == "Update") {
                int i = tbl.getSelectedRow();
                if(i >= 0) {
                    model.setValueAt(inputNama.getText(), i, 0);
                    model.setValueAt(inputNomorHp.getText(), i, 1);
                    model.setValueAt(inputC1.getText(), i, 2);
                    model.setValueAt(inputC2.getText(), i, 3);
                    model.setValueAt(inputC3.getText(), i, 4);
                    model.setValueAt(inputC4.getSelectedItem().toString(), i, 5);
                    model.setValueAt(inputC5.getText(), i, 6);
                }
            }
        }    
        clear();
        
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void inputCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputCariKeyPressed
        // TODO add your handling code here:
        DefaultTableModel obj = (DefaultTableModel) tbl.getModel();
        TableRowSorter<DefaultTableModel> obj1 = new TableRowSorter<>(obj);
        tbl.setRowSorter(obj1);
        obj1.setRowFilter(RowFilter.regexFilter(inputCari.getText()));
    }//GEN-LAST:event_inputCariKeyPressed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
        int selectedRow = tbl.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        inputNama.setText(model.getValueAt(selectedRow, 0).toString());
        inputNomorHp.setText(model.getValueAt(selectedRow, 1).toString());
        inputC1.setText(model.getValueAt(selectedRow, 2).toString());
        inputC2.setText(model.getValueAt(selectedRow, 3).toString());
        inputC3.setText(model.getValueAt(selectedRow, 4).toString());
        inputC4.setSelectedItem(model.getValueAt(selectedRow, 5).toString());
        inputC5.setText(model.getValueAt(selectedRow, 6).toString());
        btnSimpan.setText("Update");
        
    }//GEN-LAST:event_tblMouseClicked

    private void btnBersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihkanActionPerformed
        // TODO add your handling code here:
        clear();
        btnSimpan.setText("Simpan");
    }//GEN-LAST:event_btnBersihkanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        try {
            int selectedRow = tbl.getSelectedRow();
            model.removeRow(selectedRow);
            clear();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnMulaiSeleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulaiSeleksiActionPerformed
        
        // Array bobot kriteria 
        Double[] bobotKriteria = new Double[] {
          0.3, 0.15, 0.2, 0.25, 0.1  
        };
        
        // List matriks keputusan 
        List<Integer[]> matriksKeputusan = new ArrayList<>();
        
        // Tranformasi nilai C1..C5 ke bobot sub kriteria
        System.out.println("Matriks Keputusan\n");
        for (int i = 0; i < tbl.getRowCount(); i++) {
            Integer c1 = 0, c2 = 0, c3 = 0, c4 = 0,c5 = 0;
            
            // C1 
            if (Double.parseDouble(tbl.getValueAt(i, 2).toString()) >= 3.81 && Double.parseDouble(tbl.getValueAt(i, 2).toString()) <= 4.00) {
               c1 = 5; 
            } else if (Double.parseDouble(tbl.getValueAt(i, 2).toString()) >= 3.51 && Double.parseDouble(tbl.getValueAt(i, 2).toString()) <= 3.80) {
               c1 = 4;
            } else if (Double.parseDouble(tbl.getValueAt(i, 2).toString()) >= 3.31 && Double.parseDouble(tbl.getValueAt(i, 2).toString()) <= 3.50) {
                c1 = 3; 
            } else if (Double.parseDouble(tbl.getValueAt(i, 2).toString()) >= 3.00 && Double.parseDouble(tbl.getValueAt(i, 2).toString()) <= 3.30) {
                c1 = 2;
            } else if (Double.parseDouble(tbl.getValueAt(i, 2).toString()) < 3.00) {
                c1 = 1;
            }
            
            // C2
            if (Integer.parseInt(tbl.getValueAt(i, 3).toString()) >= 91 && Integer.parseInt(tbl.getValueAt(i, 3).toString()) <= 100) {
               c2 = 5; 
            } else if (Integer.parseInt(tbl.getValueAt(i, 3).toString()) >= 86 && Integer.parseInt(tbl.getValueAt(i, 3).toString()) <= 90) {
               c2 = 4;
            } else if (Integer.parseInt(tbl.getValueAt(i, 3).toString()) >= 76 && Integer.parseInt(tbl.getValueAt(i, 3).toString()) <= 85) {
               c2 = 3; 
            } else if (Integer.parseInt(tbl.getValueAt(i, 3).toString()) >= 66 && Integer.parseInt(tbl.getValueAt(i, 3).toString()) <= 75) {
               c2 = 2;
            } else if (Integer.parseInt(tbl.getValueAt(i, 3).toString()) < 65) {
               c2 = 1;
            }
            
            // C3 
            if (Integer.parseInt(tbl.getValueAt(i, 4).toString()) >= 91 && Integer.parseInt(tbl.getValueAt(i, 4).toString()) <= 100) {
               c3 = 5; 
            } else if (Integer.parseInt(tbl.getValueAt(i, 4).toString()) >= 86 && Integer.parseInt(tbl.getValueAt(i, 4).toString()) <= 90) {
               c3 = 4;
            } else if (Integer.parseInt(tbl.getValueAt(i, 4).toString()) >= 76 && Integer.parseInt(tbl.getValueAt(i, 4).toString()) <= 85) {
               c3 = 3; 
            } else if (Integer.parseInt(tbl.getValueAt(i, 4).toString()) >= 66 && Integer.parseInt(tbl.getValueAt(i, 4).toString()) <= 75) {
               c3 = 2;
            } else if (Integer.parseInt(tbl.getValueAt(i, 4).toString()) < 65) {
               c3 = 1;
            }
            
            // C4 
            if (tbl.getValueAt(i, 5).toString().equalsIgnoreCase("sangat baik")) {
                c4 = 5;
            } else if (tbl.getValueAt(i, 5).toString().equalsIgnoreCase("baik")) {
                c4 = 4;
            } else if (tbl.getValueAt(i, 5).toString().equalsIgnoreCase("cukup baik")) {
                c4 = 3;
            } else if (tbl.getValueAt(i, 5).toString().equalsIgnoreCase("kurang baik")) {
                c4 = 2;
            } else if (tbl.getValueAt(i, 5).toString().equalsIgnoreCase("tidak baik")) {
                c4 = 1;
            }
            
            if (Integer.parseInt(tbl.getValueAt(i, 6).toString()) >= 91 && Integer.parseInt(tbl.getValueAt(i, 6).toString()) <= 100) {
               c5 = 5; 
            } else if (Integer.parseInt(tbl.getValueAt(i, 6).toString()) >= 86 && Integer.parseInt(tbl.getValueAt(i, 6).toString()) <= 90) {
               c5 = 4;
            } else if (Integer.parseInt(tbl.getValueAt(i, 6).toString()) >= 76 && Integer.parseInt(tbl.getValueAt(i, 6).toString()) <= 85) {
               c5 = 3; 
            } else if (Integer.parseInt(tbl.getValueAt(i, 6).toString()) >= 66 && Integer.parseInt(tbl.getValueAt(i, 6).toString()) <= 75) {
               c5 = 2;
            } else if (Integer.parseInt(tbl.getValueAt(i, 6).toString()) < 65) {
               c5 = 1;
            }
            
            matriksKeputusan.add( new Integer[] {c1, c2, c3, c4, c5});
            
            // Console 
            System.out.println("Data ke-" + i+1);
            System.out.println("C1  : " + c1);
            System.out.println("C2  : " + c2);
            System.out.println("C3  : " + c3);
            System.out.println("C4  : " + c4);
            System.out.println("C5  : " + c5);
            System.out.println("");
        }
        
        // Cek Matriks Keputusan 
        for(Integer[] row : matriksKeputusan) {
            for (int i = 0; i < row.length; i++) {
                System.out.print(row[i] + " ");
            }
            System.out.println("");
        }
        System.out.println("");
        
        // Normalisasi 
        System.out.println("Normalisasi\n");
        
        // Maks per kolom 
        ArrayList<Integer> values = new ArrayList<>();
        ArrayList<Integer> maxValues = new ArrayList<>();
        for (int i = 0; i < 5; i ++) {
            for(int j = 0; j < matriksKeputusan.size(); j++) {
                values.add(matriksKeputusan.get(j)[i]);
            }
            maxValues.add(Collections.max(values));
            values.clear();
        }
        
        // Hitung normalisasi 
        ArrayList<ArrayList<Double>> matriksNormalisasi = new ArrayList<>(matriksKeputusan.size());
        ArrayList<Double> rowValues = new ArrayList<>();
        
        for (int i = 0; i < matriksKeputusan.size(); i++) {
            matriksNormalisasi.add(new ArrayList());
        }
        
        for (int i = 0; i < matriksKeputusan.size(); i++) {
            for (int j = 0; j < matriksKeputusan.get(i).length; j++) {
                matriksNormalisasi.get(i).add(Double.parseDouble(matriksKeputusan.get(i)[j].toString()) / maxValues.get(j));
            }
//            matriksNormalisasi.add(rowValues);
//            rowValues.clear();
        }
        
        // Cetak Matriks Normalisasi 
        System.out.println(matriksNormalisasi);
        
        
        ArrayList<Double> hasilPerhitungan = new ArrayList<>();
        Double total = 0.0;
        
        for (ArrayList<Double> row : matriksNormalisasi) {
            for (int i = 0; i < row.size(); i++) {
                total += bobotKriteria[i] * row.get(i);
            }
            hasilPerhitungan.add(total*100);
            total = 0.0;
        }
        
        // Cetak hasil perhitungan
        System.out.println(hasilPerhitungan);
        
        
        ArrayList<Boolean> isDiterima = new ArrayList<>();
        
        for (Double hasil : hasilPerhitungan) {
            if (hasil > 90.00) {
                isDiterima.add(true);
            } else {
                isDiterima.add(false);
            }
        } 
        System.out.println(isDiterima);
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            model.setValueAt(hasilPerhitungan.get(i).toString(), i, 7);
            model.setValueAt(isDiterima.get(i).toString(), i, 8);
        }
        
    }//GEN-LAST:event_btnMulaiSeleksiActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBersihkan;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnMulaiSeleksi;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JTextField inputC1;
    private javax.swing.JTextField inputC2;
    private javax.swing.JTextField inputC3;
    private javax.swing.JComboBox<String> inputC4;
    private javax.swing.JTextField inputC5;
    private javax.swing.JTextField inputCari;
    private javax.swing.JTextField inputNama;
    private javax.swing.JTextField inputNomorHp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
